### ISSUE TITLE
Increase test coverage.

### ISSUE THREAD

**Issue by burntcarrot** [burntcarrot/absorb#2]
The current test coverage sits at 76%. Is there any possibility that we can extend the test coverage further?

**Suggestions:**
- Install absorb locally using pip. See [Installation](https://github.com/burntcarrot/absorb#installation).
- Tinker around with absorb, and read documentation.

**Suggested fix/improvement:**
 Find untested code blocks using the `nox` test session, or manually by running `pytest`. Add new tests to cover untested code.

**Comment by burntcarrot** [comment]
This issue is also open for Hacktoberfest 2021. Feel free to contribute!

**Comment by Wolfy7** [comment]
Hi. I have no experience with nox but i would give it a try for hacktober :)
so if you want you can assigne this to me.

**Comment by burntcarrot** [comment]
You actually don't need to know much about nox, just run `nox -rs tests` for checking if the tests pass. I suggest you to install Poetry 1.16 first through `pip install poetry==1.1.6`, as the project uses Poetry for managing dependencies. (Nox also runs the tests using Poetry)

For now, I would suggest you to:
- Install Poetry 1.16 (as suggested above)
- Install absorb via pip, see [Installation](https://github.com/burntcarrot/absorb#installation)
- Play around with absorb (it is super easy to use, you can create to-do lists, etc.), it would be really useful for writing tests.

From October 1, you can:
- You can start writing the tests (Hacktoberfest starts).
- Create a PR. I will happily merge it and add the `hacktoberfest-accepted` label!

**Comment by burntcarrot** [comment]
@Wolfy7 Assigned the issue to you.

Have fun! Will be waiting for your PR! ❤

**Comment by Wolfy7** [comment]
Hi @burntcarrot.
I tried to run the tests as you described but i got some errors:
E>nox -rs tests 
nox > Running session tests-3.7
nox > Creating virtual environment (virtualenv) using python.exe in .nox\tests-3-7
nox > poetry install --no-dev
Installing dependencies from lock file

Package operations: 13 installs, 0 updates, 0 removals

  • Installing typing-extensions (3.10.0.0)
  • Installing zipp (3.4.1)

  AttributeError

  'Link' object has no attribute 'is_absolute'

  at d:\tool\common\python396\lib\site-packages\poetry\core\packages\file_dependency.py:33 in __init__
       29│         self._path = path
       30│         self._base = base or Path.cwd()
       31│         self._full_path = path
       32│
    →  33│         if not self._path.is_absolute():
       34│             try:
       35│                 self._full_path = self._base.joinpath(self._path).resolve()
       36│             except FileNotFoundError:
       37│                 raise ValueError("Directory {} does not exist".format(self._path))


  AttributeError

  'Link' object has no attribute 'is_absolute'

  at d:\tool\common\python396\lib\site-packages\poetry\core\packages\file_dependency.py:33 in __init__
       29│         self._path = path
       30│         self._base = base or Path.cwd()
       31│         self._full_path = path
       32│
    →  33│         if not self._path.is_absolute():
       34│             try:
       35│                 self._full_path = self._base.joinpath(self._path).resolve()
       36│             except FileNotFoundError:
       37│                 raise ValueError("Directory {} does not exist".format(self._path))

nox > Command poetry install --no-dev failed with exit code 1
nox > Session tests-3.7 failed.
nox > Running session tests-3.8
nox > Session tests-3.8 skipped: Python interpreter 3.8 not found.
nox > Ran multiple sessions:
nox > * tests-3.7: failed
nox > * tests-3.8: skipped

I have Python 3.9.6 installed could this the problem?

**Comment by Wolfy7** [comment]
It seems that problem was due to Poetry 1.1.6. with Poetry 1.1.9 nox -rs tests works as expected.

**Comment by burntcarrot** [comment]
> I have Python 3.9.6 installed could this the problem?

Yes. absorb is not tested on Python 3.9. My local environment runs Python 3.7 and the latest version of Poetry that time had issues with Python 3.7, so the team recommended to use `1.16` as a fix. 

Thanks for the heads up! I'll keep in mind that Poetry 1.16 has issues with Python 3.9.

**Comment by burntcarrot** [comment]
@Wolfy7 You may also need to add `"3.9"` to [noxfile.py](https://github.com/burntcarrot/absorb/blob/main/noxfile.py#L24), in order to make sure that the tests run.

If `nox -rs tests` is passing without any output, it means, that the tests didn't even run.

This is how the output should look like, if you're running the `tests` session:

```
================================================= test session starts =================================================
platform win32 -- Python 3.7.4, pytest-6.2.4, py-1.10.0, pluggy-0.13.1
rootdir: C:\Users\ASUS\Documents\absorb
plugins: cov-2.12.1
collected 39 items

tests\test_cli.py .                                                                                              [  2%]
tests\test_idea.py ........                                                                                      [ 23%]
tests\test_kanban.py .........                                                                                   [ 46%]
tests\test_tasks.py .....................                                                                        [100%]

----------- coverage: platform win32, python 3.7.4-final-0 -----------
Name                             Stmts   Miss Branch BrPart  Cover   Missing
----------------------------------------------------------------------------
absorb\__init__.py                   9      2      0      0    78%   11-12
absorb\config\__init__.py            0      0      0      0   100%
absorb\config\paths.py               6      0      0      0   100%
absorb\core\__init__.py              0      0      0      0   100%
absorb\core\idea\__init__.py         0      0      0      0   100%
absorb\core\idea\commands.py       101     22     24      2    81%   51-52, 76-80, 118-122, 141-145, 168-170, 183-187
absorb\core\kanban\__init__.py       0      0      0      0   100%
absorb\core\kanban\commands.py     124     29     26      2    79%   76-80, 105-113, 147->150, 151-155, 174-178, 210-218, 231-235
absorb\core\tasks\__init__.py        0      0      0      0   100%
absorb\core\tasks\commands.py      187     47     56      8    74%   55, 58-60, 78, 144, 169-173, 207, 212-221, 234-238, 257, 269-279, 292, 294-301, 318, 333-339
absorb\main.py                      15      2      2      1    82%   15, 23
absorb\utils\idea_utils.py          33      5      8      2    83%   50-53, 58
absorb\utils\kanban_utils.py        39      5     18      2    84%   35-36, 41, 61-62
absorb\utils\log_utils.py           22      4      0      0    82%   26-29
absorb\utils\tasks_utils.py         41      2     10      3    90%   58, 61->64, 70
----------------------------------------------------------------------------
TOTAL                              577    118    144     20    79%


================================================= 39 passed in 4.40s ==================================================
nox > Session tests-3.7 was successful.
nox > Running session tests-3.8
nox > Session tests-3.8 skipped: Python interpreter 3.8 not found.
nox > Ran multiple sessions:
nox > * tests-3.7: success
nox > * tests-3.8: skipped
```

**Comment by burntcarrot** [comment]
@Wolfy7 Hacktoberfest has started! You might want to work on this issue soon, as there might be many people wanting to work on this!

**Comment by Wolfy7** [comment]
@burntcarrot I will create the PR in the next few hours :)

**Comment by Wolfy7** [comment]
Opend PR: https://github.com/burntcarrot/absorb/pull/3

**Comment by burntcarrot** [comment]
Merged! Thanks for contribution!
